import { commitImmediateRevive, commitRebirth, createHpZeroCandidate, createNaturalAction, emitSsiTemporalEvent, resolveDeathWave, resolveSourceAttribution, scheduleDelayedRevive } from '../src/combat/kernel/index.ts';
import type { SessionState } from '../src/types/combat.ts';
const game=():SessionState=>({runtime:{},tokens:[],battle:{over:false},events:{}} as unknown as SessionState);
const source=resolveSourceAttribution({immediateSource:'killer-iid',trueSelf:'killer-self'});
const unit=(iid:number,kind='collection-unit')=>({id:`u${iid}`,iid,trueSelfId:`self${iid}`,lifeSerial:1,side:'enemy',cx:0,cy:iid,hp:0,hpMax:100,alive:false,lifeState:'hp-zero',entityKind:kind,statuses:[]} as any);
const kill=(g:SessionState,targets:any[])=>{const action=createNaturalAction(g); for(const target of targets)createHpZeroCandidate(g,target,action,source,'damage',100); return resolveDeathWave(g);};

test('five deterministic qualifying deaths enter only the first life into reincarnation',()=>{const g=game(),units=[1,2,3,4,5].map(unit);g.tokens=units;const deaths=kill(g,units);expect(deaths.map(d=>d.targetIid)).toEqual([1,2,3,4,5]);const records=(g.runtime as any).reincarnationByDeathId;expect(records[deaths[0]!.deathId].state).toBe('entered');expect(records[deaths[1]!.deathId].state).toBe('waiting');expect((g.runtime as any).qualifyingDeathOrdinal).toBe(5);});
test('summon death does not advance reincarnation ordinal',()=>{const g=game(),summon=unit(1,'summon');summon.isMinion=true;delete summon.trueSelfId;delete summon.lifeSerial;g.tokens=[summon];kill(g,[summon]);expect((g.runtime as any).qualifyingDeathOrdinal??0).toBe(0);});
test('reincarnation blocks normal revive and rebirth creates a new incarnation',()=>{const g=game(),units=[1,2,3,4,5].map(unit);g.tokens=units;const deaths=kill(g,units);const death=deaths[0]!;expect(commitImmediateRevive(g,units[0],{death,hpPolicy:{kind:'flat',value:5},ragePolicy:'reset',buffPolicy:'clear-temporary',positionPolicy:'preserve',source}).reason).toBe('entered-reincarnation');const result=commitRebirth(g,{deathId:death.deathId,trueSelfId:'self1',newIid:99,authority:'rebirth',effectAllowsRebirth:true,spawn:{side:'ally',cx:1,cy:1},template:{...units[0],statuses:[{id:'temporary'}]} as any,policies:{hp:'full',rage:0}});expect(result).toMatchObject({committed:true,newIid:99,incarnationSerial:2});expect(g.tokens.at(-1)?.trueSelfId).toBe('self1');expect(g.tokens.at(-1)?.statuses).toEqual([]);expect((g.runtime as any).combatEvents.some((event:any)=>event.type==='REVIVE_COMMITTED')).toBe(false);});
test('SSI natural completion drives production delayed revive clock',()=>{const g=game(),target=unit(7);g.tokens=[target];const [death]=kill(g,[target]);const entry=scheduleDelayedRevive(g,{deathId:death!.deathId,targetIid:7,trueSelfId:'self7',deadLifeSerial:1,targetSide:'enemy',requestSource:source,clockPolicy:'global-natural-actions',delayAmount:1,eligibilityPolicy:'default',revivePolicies:{hpPolicy:{kind:'flat',value:10},ragePolicy:'reset',buffPolicy:'clear-temporary',positionPolicy:'preserve'}});emitSsiTemporalEvent(g,{type:'NATURAL_ACTION_COMPLETED',actorSide:'ally',actorIid:1,slot:1,cursorSnapshot:{ally:1,enemy:0},sidePassSerial:0,globalCycleSerial:0,actionId:'action-x'});expect(entry.state).toBe('committed');expect(target.lifeSerial).toBe(2);});
