import { advanceDelayedReviveClock, collectDeathPreventionDecisions, commitImmediateRevive, createHpZeroCandidate, createNaturalAction, evaluateBattleEnd, executeActionTransaction, registerDeathPrevention, resolveDeathWave, resolveSourceAttribution, scheduleDelayedRevive } from '../src/combat/kernel/index.ts';
import type { SessionState } from '../src/types/combat.ts';
const game = (): SessionState => ({ runtime: {}, tokens: [], battle: { over: false }, events: {} } as unknown as SessionState);
const source = resolveSourceAttribution({ immediateSource: 'source', trueSelf: 'killer' });
const unit = (iid: number, side: 'ally'|'enemy' = 'enemy', leader = false) => ({ id: `u${iid}`, iid, trueSelfId: `self${iid}`, lifeSerial: 1, side, cx: 0, cy: iid, hp: 0, hpMax: 100, alive: false, lifeState: 'hp-zero', isLeader: leader, statuses: [] } as any);

test('action transaction validates before committing a cost and commits once', () => {
 const g=game(), actor={alive:true} as any; let commits=0;
 const failed=executeActionTransaction({game:g,identity:createNaturalAction(g),actor,targets:[],reserveCosts:()=>[{id:'ae',validate:()=>true,commit:()=>commits++,release:()=>{}}],resolvePayload:()=>1});
 expect(failed.ok).toBe(false); expect(commits).toBe(0);
 const ok=executeActionTransaction({game:g,identity:createNaturalAction(g),actor,targets:[actor],reserveCosts:()=>[{id:'ae',validate:()=>true,commit:()=>commits++,release:()=>{}}],resolvePayload:()=>1});
 expect(ok.ok).toBe(true); expect(commits).toBe(1);
});
test('prevention collection uses authority, priority and stable registration order',()=>{ const g=game(), target=unit(1); g.tokens=[target]; const c=createHpZeroCandidate(g,target,createNaturalAction(g),source,'damage',100); registerDeathPrevention(g,()=>({prevent:true,hp:4,effectId:'normal',authority:'normal',explicitPriority:99})); registerDeathPrevention(g,()=>({prevent:true,hp:2,effectId:'law',authority:'law'})); expect(collectDeathPreventionDecisions(g,c).map(x=>x.effectId)).toEqual(['law','normal']); resolveDeathWave(g); expect(target.hp).toBe(2); expect(target.lifeSerial).toBe(1); });
test('persistent lifecycle dedupes death and immediate revive consumes canonical death',()=>{ const g=game(), target=unit(2); g.tokens=[target]; const id=createNaturalAction(g); createHpZeroCandidate(g,target,id,source,'damage',100); createHpZeroCandidate(g,target,id,source,'damage',100); const [death]=resolveDeathWave(g); expect(resolveDeathWave(g)).toEqual([]); expect((g.runtime as any).combatEvents.filter((e:any)=>e.type==='HP_ZERO')).toHaveLength(1); const request={death:death!,hpPolicy:{kind:'flat' as const,value:20},ragePolicy:'preserve' as const,aePolicy:'preserve' as const,buffPolicy:'preserve' as const,positionPolicy:'preserve' as const,source}; expect(commitImmediateRevive(g,target,request).committed).toBe(true); expect(target.lifeSerial).toBe(2); expect(commitImmediateRevive(g,target,request).committed).toBe(false); });
test('delayed revive is deterministic and battle end blocks leader queue',()=>{ const g=game(), leader=unit(3,'ally',true), enemy={...unit(4,'enemy',true),hp:10,alive:true,lifeState:'alive'}; g.tokens=[leader,enemy]; createHpZeroCandidate(g,leader,createNaturalAction(g),source,'damage',100); const [death]=resolveDeathWave(g); scheduleDelayedRevive(g,{deathId:death!.deathId,targetIid:leader.iid,trueSelfId:leader.trueSelfId,deadLifeSerial:1,requestSource:source,clockPolicy:'global-natural-actions',delayAmount:1,eligibilityPolicy:'default',revivePolicies:{hpPolicy:{kind:'flat',value:10},ragePolicy:'preserve',aePolicy:'preserve',buffPolicy:'preserve',positionPolicy:'preserve'}}); expect(evaluateBattleEnd(g,[death!]).winner).toBe('enemy'); expect(advanceDelayedReviveClock(g,'global-natural-actions')[0]?.state).toBe('cancelled'); });
