import { advanceDelayedReviveClock, beginActionExecution, collectDeathPreventionDecisions, commitImmediateRevive, compareDeathAuthority, createHpZeroCandidate, createNaturalAction, currentActionExecution, endActionExecution, evaluateBattleEnd, executeActionTransaction, finalizeCombatAction, nextEventSerial, registerDeathPrevention, resolveDeathWave, resolveSourceAttribution, scheduleDelayedRevive, withActionExecution } from '../src/combat/kernel/index.ts';
import { compareRuleTagPriority } from '../src/combat/tag-aliases.ts';
import { nextTurnInterleaved } from '../src/turns/interleaved.ts';
import type { SessionState } from '../src/types/combat.ts';
const game = (): SessionState => ({ runtime: {}, tokens: [], battle: { over: false }, events: {} } as unknown as SessionState);
const source = resolveSourceAttribution({ immediateSource: 'source', trueSelf: 'killer' });
const unit = (iid: number, side: 'ally'|'enemy' = 'enemy', leader = false) => ({ id: `u${iid}`, iid, trueSelfId: `self${iid}`, lifeSerial: 1, side, cx: 0, cy: iid, hp: 0, hpMax: 100, alive: false, lifeState: 'hp-zero', isLeader: leader, statuses: [] } as any);

test('action transaction validates before committing a cost and commits once', () => {
 const g=game(), actor={alive:true} as any; let commits=0;
 const failed=executeActionTransaction({game:g,identity:createNaturalAction(g),actor,targets:[],reserveCosts:()=>[{id:'ae',validate:()=>true,commit:()=>commits++,release:()=>{}}],resolvePayload:()=>1});
 expect(failed.ok).toBe(false); expect(commits).toBe(0);
 const ok=executeActionTransaction({game:g,identity:createNaturalAction(g),actor,targets:[actor],reserveCosts:()=>[{id:'ae',validate:()=>true,commit:()=>commits++,release:()=>{}}],resolvePayload:()=>1});
 expect(ok.ok).toBe(true); expect(commits).toBe(1);
});
test('finalization correlates payload events from ACTION_START and reports the exact serial range',()=>{ const g=game(); const identity=createNaturalAction(g); const ctx=beginActionExecution(g,identity); const serial=nextEventSerial(g); ((g.runtime as any).combatEvents ??= []).push({type:'DAMAGE_BATCH_RESOLVED',eventSerial:serial,actionId:identity.actionId,chainId:identity.chainId,hpAllocation:[{targetIid:1,hpDamage:4}]}); endActionExecution(g,ctx); const result=finalizeCombatAction(g,ctx); expect(result.committedTargetAggregates).toEqual([{targetIid:1,hpDamage:4}]); expect(result.emittedEventSerialRange).toEqual({first:ctx.startEventSerial,last:expect.any(Number)}); expect(result.emittedEventSerialRange.last).toBeGreaterThan(serial); });
test('canonical action finalization is idempotent and emits one ACTION_END',()=>{ const g=game(); const identity=createNaturalAction(g); const ctx=beginActionExecution(g,identity); endActionExecution(g,ctx); const first=finalizeCombatAction(g,ctx); const second=finalizeCombatAction(g,ctx); expect(second).toBe(first); expect((g.runtime as any).combatEvents.filter((event:any)=>event.type==='ACTION_END')).toHaveLength(1); });
test('throwing payload always pops its action context and does not finalize',()=>{ const g=game(), identity=createNaturalAction(g); expect(()=>withActionExecution(g,identity,()=>{throw new Error('payload');})).toThrow('payload'); expect(currentActionExecution(g)).toBeNull(); expect(((g.runtime as any).combatEvents ?? []).filter((event:any)=>event.type==='ACTION_END')).toHaveLength(0); });
test('prevention collection uses authority, priority and stable registration order',()=>{ const g=game(), target=unit(1); g.tokens=[target]; const c=createHpZeroCandidate(g,target,createNaturalAction(g),source,'damage',100); registerDeathPrevention(g,()=>({prevent:true,hp:4,effectId:'normal',authority:'normal',explicitPriority:99})); registerDeathPrevention(g,()=>({prevent:true,hp:2,effectId:'rule',authority:'global-rule'})); expect(collectDeathPreventionDecisions(g,c).map(x=>x.effectId)).toEqual(['rule','normal']); resolveDeathWave(g); expect(target.hp).toBe(2); expect(target.lifeSerial).toBe(1); });
test('persistent lifecycle dedupes death and immediate revive consumes canonical death',()=>{ const g=game(), target=unit(2); g.tokens=[target]; const id=createNaturalAction(g); createHpZeroCandidate(g,target,id,source,'damage',100); createHpZeroCandidate(g,target,id,source,'damage',100); const [death]=resolveDeathWave(g); expect(resolveDeathWave(g)).toEqual([]); expect((g.runtime as any).combatEvents.filter((e:any)=>e.type==='HP_ZERO')).toHaveLength(1); const request={death:death!,hpPolicy:{kind:'flat' as const,value:20},ragePolicy:'preserve' as const,aePolicy:'preserve' as const,buffPolicy:'preserve' as const,positionPolicy:'preserve' as const,source}; expect(commitImmediateRevive(g,target,request).committed).toBe(true); expect(target.lifeSerial).toBe(2); expect(commitImmediateRevive(g,target,request).committed).toBe(false); });
test('delayed revive is deterministic and battle end blocks leader queue',()=>{ const g=game(), leader=unit(3,'ally',true), enemy={...unit(4,'enemy',true),hp:10,alive:true,lifeState:'alive'}; g.tokens=[leader,enemy]; createHpZeroCandidate(g,leader,createNaturalAction(g),source,'damage',100); const [death]=resolveDeathWave(g); scheduleDelayedRevive(g,{deathId:death!.deathId,targetIid:leader.iid,trueSelfId:leader.trueSelfId,deadLifeSerial:1,requestSource:source,clockPolicy:'global-natural-actions',delayAmount:1,eligibilityPolicy:'default',revivePolicies:{hpPolicy:{kind:'flat',value:10},ragePolicy:'preserve',aePolicy:'preserve',buffPolicy:'preserve',positionPolicy:'preserve'}}); expect(evaluateBattleEnd(g,[death!]).winner).toBe('enemy'); expect(advanceDelayedReviveClock(g,'global-natural-actions')[0]?.state).toBe('cancelled'); });

test('prevented life can open a second lethal ticket and then confirm without incrementing life',()=>{ const g=game(), target=unit(5); g.tokens=[target]; let available=true; registerDeathPrevention(g,()=>available?{prevent:true,hp:1,effectId:'once'}:null); const action=createNaturalAction(g); createHpZeroCandidate(g,target,action,source,'damage',100); resolveDeathWave(g); expect(target.lifeSerial).toBe(1); available=false; target.hp=0; createHpZeroCandidate(g,target,action,source,'damage',1); expect(resolveDeathWave(g)).toHaveLength(1); expect((g.runtime as any).combatEvents.filter((e:any)=>e.type==='HP_ZERO')).toHaveLength(2); });

test('wave emits all confirmations before any kill credit and uses canonical slot ordering',()=>{ const g=game(), a=unit(6), b=unit(7); a.cx=2;a.cy=0;b.cx=0;b.cy=0;g.tokens=[a,b]; const action=createNaturalAction(g); createHpZeroCandidate(g,a,action,source,'damage',1);createHpZeroCandidate(g,b,action,source,'damage',1); const records=resolveDeathWave(g); expect(records.map(r=>r.targetIid)).toEqual([7,6]); const types=(g.runtime as any).combatEvents.map((e:any)=>e.type); expect(Math.max(...types.map((t:string,i:number)=>t==='DEATH_CONFIRMED'?i:-1))).toBeLessThan(Math.min(...types.map((t:string,i:number)=>t==='KILL_CREDIT_GRANTED'?i:Infinity))); });

test('death authority delegates to shared rule comparator',()=>{ expect(compareDeathAuthority('axiom-rule','global-rule')).toBe(compareRuleTagPriority('axiom-rule','global-rule')); });

test('serialized canonical death can revive once and preserve AE',()=>{ const g=game(), target=unit(8); target.ae=9;g.tokens=[target];createHpZeroCandidate(g,target,createNaturalAction(g),source,'damage',1); const serialized=JSON.parse(JSON.stringify(resolveDeathWave(g)[0])); expect(commitImmediateRevive(g,target,{death:serialized,hpPolicy:{kind:'flat',value:3},ragePolicy:'preserve',buffPolicy:'preserve-all',positionPolicy:'preserve',source}).committed).toBe(true);expect(target.lifeSerial).toBe(2);expect(target.ae).toBe(9); });

test('both confirmed leaders draw and SSI stops without moving cursor',()=>{ const g=game(), ally=unit(9,'ally',true), enemy=unit(10,'enemy',true);g.tokens=[ally,enemy];const action=createNaturalAction(g);createHpZeroCandidate(g,ally,action,source,'damage',1);createHpZeroCandidate(g,enemy,action,source,'damage',1);const wave=resolveDeathWave(g);expect(evaluateBattleEnd(g,wave).winner).toBe('draw');g.turn={nextSide:'ALLY',lastPos:{ALLY:0,ENEMY:0},wrapCount:{ALLY:0,ENEMY:0},actedNatural:{ALLY:[],ENEMY:[]},turnCount:0,cycle:0,slotCount:9} as any;expect(nextTurnInterleaved(g)).toBeNull();expect((g.turn as any).turnCount).toBe(0); });