import { commitImmediateRevive, commitRebirthEffect, createHpZeroCandidate, createNaturalAction, emitSsiTemporalEvent, resolveDeathWave, resolveSourceAttribution, scheduleDelayedRevive } from '../src/combat/kernel/index.ts';
import type { SessionState } from '../src/types/combat.ts';
import { dispatchGameplayTags } from '../src/combat/tag-dispatch.ts';
const game=():SessionState=>({runtime:{},tokens:[],battle:{over:false},events:{}} as unknown as SessionState);
const source=resolveSourceAttribution({immediateSource:'killer-iid',trueSelf:'killer-self'});
const unit=(iid:number,kind='collection-unit')=>({id:`u${iid}`,iid,trueSelfId:`self${iid}`,incarnationSerial:1,lifeSerial:1,side:'enemy',cx:0,cy:iid,hp:0,hpMax:100,alive:false,lifeState:'hp-zero',entityKind:kind,statuses:[]} as any);
const kill=(g:SessionState,targets:any[])=>{const action=createNaturalAction(g); for(const target of targets)createHpZeroCandidate(g,target,action,source,'damage',100); return resolveDeathWave(g);};

test('five deterministic qualifying deaths enter only the first life into reincarnation',()=>{const g=game(),units=[1,2,3,4,5].map(iid=>unit(iid));g.tokens=units;const deaths=kill(g,units);expect(deaths.map(d=>d.targetIid)).toEqual([1,2,3,4,5]);const records=(g.runtime as any).reincarnationByDeathId;expect(records[deaths[0]!.deathId].state).toBe('entered');expect(records[deaths[1]!.deathId].state).toBe('waiting');expect((g.runtime as any).qualifyingDeathOrdinal).toBe(5);});
test('summon death does not advance reincarnation ordinal',()=>{const g=game(),summon=unit(1,'summon');summon.isMinion=true;delete summon.trueSelfId;delete summon.lifeSerial;g.tokens=[summon];kill(g,[summon]);expect((g.runtime as any).qualifyingDeathOrdinal??0).toBe(0);});
test('reincarnation blocks normal revive and production rebirth allocates a new incarnation iid',()=>{const g=game(),units=[1,2,3,4,5].map(iid=>unit(iid));g.tokens=units;const deaths=kill(g,units);const death=deaths[0]!;expect(commitImmediateRevive(g,units[0],{death,hpPolicy:{kind:'flat',value:5},ragePolicy:'reset',buffPolicy:'clear-temporary',positionPolicy:'preserve',source}).reason).toBe('entered-reincarnation');const result=commitRebirthEffect(g,death.deathId,'test-rebirth',{side:'ally',cx:1,cy:1},{...units[0],statuses:[{id:'temporary'}]} as any,{hp:'full',rage:0});expect(result).toMatchObject({committed:true,newIid:6,incarnationSerial:2});expect(g.tokens.at(-1)?.trueSelfId).toBe('self1');expect(g.tokens.at(-1)?.statuses).toEqual([]);expect((g.runtime as any).combatEvents.some((event:any)=>event.type==='REBIRTH_RETIRED')).toBe(true);expect((g.runtime as any).combatEvents.some((event:any)=>event.type==='REVIVE_COMMITTED')).toBe(false);});
test('SSI natural completion drives production delayed revive clock',()=>{const g=game(),target=unit(7);g.tokens=[target];const [death]=kill(g,[target]);const entry=scheduleDelayedRevive(g,{deathId:death!.deathId,targetIid:7,trueSelfId:'self7',deadLifeSerial:1,targetSide:'enemy',requestSource:source,clockPolicy:'global-natural-actions',delayAmount:1,eligibilityPolicy:'default',revivePolicies:{hpPolicy:{kind:'flat',value:10},ragePolicy:'reset',buffPolicy:'clear-temporary',positionPolicy:'preserve'}});emitSsiTemporalEvent(g,{type:'NATURAL_ACTION_COMPLETED',actorSide:'ally',actorIid:1,slot:1,cursorSnapshot:{ally:1,enemy:0},sidePassSerial:0,globalCycleSerial:0,actionId:'action-x'});expect(entry.state).toBe('committed');expect(target.lifeSerial).toBe(2);});
test('production gameplay tag dispatch schedules an incarnation-aware delayed revive',()=>{const g=game(),actor=unit(8),target=unit(9,'enemy');g.tokens=[actor,target];const [death]=kill(g,[target]);const result=dispatchGameplayTags(['delayed-revive'],{game:g,attacker:actor,payload:{deathRecord:death,delayedRevive:{delayAmount:1,clockPolicy:'global-natural-actions',target:'death-target',hpPolicy:{kind:'flat',value:7},ragePolicy:'reset',buffPolicy:'clear-temporary',positionPolicy:'preserve',authority:'configured-test'}}});expect(result.applied).toContain('delayed-revive');expect((g.runtime as any).delayedRevives[0]).toMatchObject({deathId:death!.deathId,incarnationSerial:1,dueValue:1,state:'queued'});emitSsiTemporalEvent(g,{type:'NATURAL_ACTION_COMPLETED',actorSide:'ally',actorIid:8,slot:0,cursorSnapshot:{ally:0,enemy:0},sidePassSerial:0,globalCycleSerial:0,actionId:'action-real'});expect(target.lifeState).toBe('alive');expect(target.hp).toBe(7);});
