import { assertStableSnapshotBoundary, serializeCombatSnapshot, type SnapshotEnvelope, type StableBoundary, type TemporalAnchor } from './temporal-contract.ts';
export const AXIOM_IDS = Object.freeze(['reincarnation', 'heavenly-thunder', 'divine-nature', 'light-shadow-river'] as const);
export type AxiomId = typeof AXIOM_IDS[number];
export type ModeId = 'pve' | 'arena' | 'chess';
export type CanonicalEventType = 'ACTION_FINALIZED' | 'DAMAGE_COMMITTED' | 'HEAL_COMMITTED' | 'STATUS_APPLIED' | 'STATUS_REMOVED' | 'RESOURCE_CHANGED' | 'TURN_GRANTED' | 'TURN_CONSUMED' | 'SUMMON_COMMITTED' | 'DEATH_CONFIRMED' | 'REVIVE_COMMITTED' | 'DELAYED_REVIVE_SCHEDULED' | 'DELAYED_REVIVE_RESOLVED' | 'REINCARNATION_ENTERED' | 'REBIRTH_CLAIM_WINDOW_OPENED' | 'REBIRTH_COMMITTED' | 'BATTLE_END' | 'TRANSGRESSION_RECORDED' | 'MECHANIC_CLAIM_SUBMITTED';
export interface AxiomEventPayloadMap { ACTION_FINALIZED: { actionId: string | number }; DAMAGE_COMMITTED: { actionId: string | number }; HEAL_COMMITTED: { actionId: string | number }; STATUS_APPLIED: { targetIid: string | number }; STATUS_REMOVED: { targetIid: string | number }; RESOURCE_CHANGED: { targetIid: string | number }; TURN_GRANTED: { actorIid: string | number }; TURN_CONSUMED: { actorIid: string | number }; SUMMON_COMMITTED: { summonIid: string | number }; DEATH_CONFIRMED: { deathId: string }; REVIVE_COMMITTED: { deathId: string }; DELAYED_REVIVE_SCHEDULED: { deathId: string }; DELAYED_REVIVE_RESOLVED: { deathId: string }; REINCARNATION_ENTERED: { trueSelfId: string }; REBIRTH_CLAIM_WINDOW_OPENED: { trueSelfId: string }; REBIRTH_COMMITTED: { trueSelfId: string }; BATTLE_END: { winner: string | null }; TRANSGRESSION_RECORDED: { eventId: string }; MECHANIC_CLAIM_SUBMITTED: { claimId: string } }
export type AxiomCommandType = keyof AxiomCommandPayloadMap;
export interface AxiomCommandPayloadMap { 'record-death': { deathId: string }; 'enter-reincarnation': { trueSelfId: string }; 'finalize-rebirth': { trueSelfId: string }; 'depart-true-self': { trueSelfId: string }; 'commit-rebirth': { trueSelfId: string }; 'record-transgression': { eventId: string }; 'issue-judgment': { sentenceId: string }; 'route-judgment': { sentenceId: string }; 'request-lightning-damage': { sentenceId: string; targetIid: string | number }; 'submit-protected-claim': { claimId: string }; 'create-temporal-anchor': { anchorId: string } }
export interface AxiomQueryMap { 'combat-state': unknown; 'true-self-record': unknown; 'transgression-ledger': unknown }
export type AxiomCommand<K extends AxiomCommandType = AxiomCommandType> = { readonly type: K; readonly payload: Readonly<AxiomCommandPayloadMap[K]> };
export interface AxiomCommandReceipt { readonly command: AxiomCommandType; readonly committed: true; readonly receiptId: string }
export type AxiomActivationPolicy = 'global' | 'trait' | 'participant-required';
export interface ReadonlyAxiomContext { readonly mode: ModeId; readonly sourceTrueSelfId?: string; readonly read: <K extends keyof AxiomQueryMap>(query: K) => AxiomQueryMap[K]; readonly submit: <K extends AxiomCommandType>(command: AxiomCommand<K>) => AxiomCommandReceipt }
export interface AxiomRuntime { onEvent<K extends CanonicalEventType>(event: K, payload: Readonly<AxiomEventPayloadMap[K]>): void }
export interface AxiomDefinition { readonly id: AxiomId; readonly version: number; readonly activationPolicy: AxiomActivationPolicy; readonly supportedModes: readonly ModeId[]; readonly observedEvents: readonly CanonicalEventType[]; readonly allowedCommands: readonly AxiomCommandType[]; createRuntime(context: ReadonlyAxiomContext): AxiomRuntime }
const definitions = new Map<AxiomId, AxiomDefinition>();
const commandHandlers = new Map<AxiomCommandType, (command: AxiomCommand) => AxiomCommandReceipt>();
export function registerAxiomDefinition(definition: AxiomDefinition): void { if (!AXIOM_IDS.includes(definition.id) || definitions.has(definition.id)) throw new Error(`[axiom] duplicate or unsupported definition ${definition.id}`); definitions.set(definition.id, Object.freeze(definition)); }
export function registerAxiomCommandHandler(type: AxiomCommandType, handler: (command: AxiomCommand) => AxiomCommandReceipt): void { if (commandHandlers.has(type)) throw new Error(`[axiom] duplicate command handler ${type}`); commandHandlers.set(type, handler); }
export function listAxiomDefinitions(): readonly AxiomDefinition[] { return [...definitions.values()]; }
export class AxiomModuleSet {
  readonly loaded = new Set<AxiomId>(); readonly active: Array<{ definition: AxiomDefinition; runtime: AxiomRuntime; sourceTrueSelfId?: string }> = []; private temporal?: { anchors: Array<{ anchor: TemporalAnchor; serializedState: string }> }; private disposed = false;
  constructor(readonly mode: ModeId, private readonly stableBoundary: () => StableBoundary | boolean = () => true, private readonly readState: <K extends keyof AxiomQueryMap>(query: K) => AxiomQueryMap[K] = () => undefined as never) { for (const definition of definitions.values()) if (definition.activationPolicy === 'global' && definition.supportedModes.includes(mode)) this.load(definition.id); }
  get snapshotCount(): number { return this.temporal?.anchors.length ?? 0; }
  load(id: AxiomId, sourceTrueSelfId?: string): void { if (this.disposed) throw new Error('[axiom] session runtime is disposed'); const definition = definitions.get(id); if (!definition || !definition.supportedModes.includes(this.mode)) throw new Error(`[axiom] unavailable module ${id} in ${this.mode}`); const key = `${id}:${sourceTrueSelfId ?? ''}`; if (this.active.some(item => `${item.definition.id}:${item.sourceTrueSelfId ?? ''}` === key)) return; if (definition.activationPolicy === 'trait' && !sourceTrueSelfId) throw new Error(`[axiom] ${id}: trait activation requires a source True Self`); const submit = <K extends AxiomCommandType>(command: AxiomCommand<K>): AxiomCommandReceipt => { if (!definition.allowedCommands.includes(command.type)) throw new Error(`[axiom] ${id}: unauthorized command ${command.type}`); if (command.type === 'create-temporal-anchor') { const boundary = this.stableBoundary(); if (boundary === false) throw new Error('[axiom] temporal anchor requires a stable boundary'); if (boundary !== true) assertStableSnapshotBoundary(boundary); const anchorId = (command.payload as unknown as AxiomCommandPayloadMap['create-temporal-anchor']).anchorId; const envelope = this.readState('combat-state') as SnapshotEnvelope; if (!anchorId || !envelope?.snapshotId || this.temporal?.anchors.some(item => item.anchor.anchorId === anchorId)) throw new Error('[axiom] temporal anchor id must be unique and state must be a canonical snapshot'); const anchor = Object.freeze({ anchorId, snapshotId: envelope.snapshotId, branchId: envelope.state.branch.branchId, createdEventSerial: envelope.state.serials.event ?? 0 }); (this.temporal ??= { anchors: [] }).anchors.push(Object.freeze({ anchor, serializedState: serializeCombatSnapshot(envelope) })); return Object.freeze({ command: command.type, committed: true, receiptId: anchorId }); } const handler = commandHandlers.get(command.type); if (!handler) throw new Error(`[axiom] ${id}: missing handler for ${command.type}`); return handler(command as AxiomCommand); }; const runtime = definition.createRuntime(Object.freeze({ mode: this.mode, sourceTrueSelfId, read: this.readState, submit })); this.loaded.add(id); this.active.push({ definition, runtime, sourceTrueSelfId }); }
  publish<K extends CanonicalEventType>(event: K, payload: Readonly<AxiomEventPayloadMap[K]>): void { if (this.disposed) return; for (const item of this.active) if (item.definition.observedEvents.includes(event)) item.runtime.onEvent(event, payload); }
  dispose(): void { this.disposed = true; this.active.length = 0; this.loaded.clear(); this.temporal = undefined; }
}
export interface AxiomParticipantManifest { readonly leaders?: readonly { requiresAxiom?: AxiomId }[]; readonly decks?: readonly { requiresAxiom?: AxiomId }[]; readonly npcRoster?: readonly { requiresAxiom?: AxiomId }[]; readonly scriptedReinforcements?: readonly { requiresAxiom?: AxiomId }[]; readonly summonDefinitions?: readonly { requiresAxiom?: AxiomId }[]; readonly replacementDefinitions?: readonly { requiresAxiom?: AxiomId }[]; readonly transformationDefinitions?: readonly { requiresAxiom?: AxiomId }[]; readonly undeployedDeck?: readonly { requiresAxiom?: AxiomId }[] }
export function preflightAxiomModules(set: AxiomModuleSet, manifest: AxiomParticipantManifest): void { for (const group of [manifest.leaders, manifest.decks, manifest.undeployedDeck, manifest.npcRoster, manifest.scriptedReinforcements, manifest.summonDefinitions, manifest.replacementDefinitions, manifest.transformationDefinitions]) for (const participant of group ?? []) if (participant.requiresAxiom) set.load(participant.requiresAxiom); }
const eventRuntime = (context: ReadonlyAxiomContext, command?: AxiomCommandType): AxiomRuntime => ({ onEvent: (_event, payload) => { if (command) context.submit({ type: command, payload } as never); } });
for (const definition of [
 { id: 'reincarnation', version: 1, activationPolicy: 'global', supportedModes: ['pve','arena','chess'], observedEvents: ['DEATH_CONFIRMED'], allowedCommands: ['record-death'], createRuntime: (context: ReadonlyAxiomContext) => eventRuntime(context, 'record-death') },
 { id: 'heavenly-thunder', version: 1, activationPolicy: 'global', supportedModes: ['pve','arena','chess'], observedEvents: ['TRANSGRESSION_RECORDED'], allowedCommands: ['record-transgression'], createRuntime: (context: ReadonlyAxiomContext) => eventRuntime(context, 'record-transgression') },
 { id: 'divine-nature', version: 1, activationPolicy: 'trait', supportedModes: ['pve','arena','chess'], observedEvents: ['MECHANIC_CLAIM_SUBMITTED'], allowedCommands: ['submit-protected-claim'], createRuntime: (context: ReadonlyAxiomContext) => eventRuntime(context, 'submit-protected-claim') },
] as const) registerAxiomDefinition(definition);