export interface TemporalBranchIdentity { readonly branchId: string; readonly parentBranchId: string | null; readonly forkedFromEventSerial: number }
export interface TemporalAnchor { readonly anchorId: string; readonly snapshotId: string; readonly branchId: string; readonly createdEventSerial: number }
export interface AnchorConsumptionRecord { readonly anchorId: string; readonly fromBranchId: string; readonly restoredBranchId: string; readonly eventSerial: number }
export class TemporalAnchorLedger { readonly consumedAnchorIds = new Set<string>(); readonly consumptionRecords: AnchorConsumptionRecord[] = []; consume(record: AnchorConsumptionRecord): void { if (this.consumedAnchorIds.has(record.anchorId)) throw new Error(`[temporal] anchor already consumed: ${record.anchorId}`); this.consumedAnchorIds.add(record.anchorId); this.consumptionRecords.push(Object.freeze({ ...record })); } }
export interface StableBoundary { readonly actionFinalized: boolean; readonly deathWaveFinalized: boolean; readonly immediateReviveFinalized: boolean; readonly openHpZeroCandidates: number; readonly summonInsertionPending: boolean; readonly occupancyMutationPending: boolean; readonly beforeNextNaturalActor: boolean }
export interface CanonicalCombatSnapshot { readonly tokens: readonly unknown[]; readonly identities: readonly unknown[]; readonly hp: Readonly<Record<string, number>>; readonly hpMax: Readonly<Record<string, number>>; readonly shields: readonly unknown[]; readonly statuses: readonly unknown[]; readonly resources: Readonly<Record<string, unknown>>; readonly positions: readonly unknown[]; readonly queuedSummons: readonly unknown[]; readonly occupancy: readonly unknown[]; readonly fields: readonly unknown[]; readonly cooldowns: Readonly<Record<string, unknown>>; readonly stances: Readonly<Record<string, string>>; readonly forms: Readonly<Record<string, string>>; readonly lifeStates: Readonly<Record<string, string>>; readonly deathRecords: readonly unknown[]; readonly reviveQueues: readonly unknown[]; readonly reincarnationRecords: readonly unknown[]; readonly rebirthRecords: readonly unknown[]; readonly ssi: Readonly<Record<string, unknown>>; readonly serials: Readonly<Record<string, number>>; readonly rng: Readonly<{ seed: number; callCount: number }>; readonly battleEnd: Readonly<Record<string, unknown>>; readonly branch: TemporalBranchIdentity }
export interface SnapshotEnvelope { readonly schemaVersion: 1; readonly snapshotId: string; readonly state: CanonicalCombatSnapshot }
const stable = (value: unknown): unknown => Array.isArray(value) ? value.map(stable) : value && typeof value === 'object' ? Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => [key, stable(child)])) : value;
export function serializeCombatSnapshot(envelope: SnapshotEnvelope): string { return JSON.stringify(stable(envelope)); }
export function deserializeCombatSnapshot(serialized: string): SnapshotEnvelope { const value = JSON.parse(serialized) as SnapshotEnvelope; if (value.schemaVersion !== 1 || !value.snapshotId || !value.state?.branch?.branchId) throw new Error('[temporal] invalid snapshot envelope'); return value; }
export function assertStableSnapshotBoundary(boundary: StableBoundary): void { if (!boundary.actionFinalized || !boundary.deathWaveFinalized || !boundary.immediateReviveFinalized || boundary.openHpZeroCandidates !== 0 || boundary.summonInsertionPending || boundary.occupancyMutationPending || !boundary.beforeNextNaturalActor) throw new Error('[temporal] snapshot requested outside stable natural-turn boundary'); }
export function restoreTemporalAnchor(anchor: TemporalAnchor, envelope: SnapshotEnvelope, ledger: TemporalAnchorLedger, currentBranchId: string, newBranchId: string): SnapshotEnvelope { if (ledger.consumedAnchorIds.has(anchor.anchorId)) throw new Error(`[temporal] anchor already consumed: ${anchor.anchorId}`); if (anchor.snapshotId !== envelope.snapshotId || anchor.branchId !== envelope.state.branch.branchId || currentBranchId !== anchor.branchId || !newBranchId || newBranchId === currentBranchId) throw new Error('[temporal] anchor validation failed'); const restored = { ...envelope, state: { ...envelope.state, branch: { branchId: newBranchId, parentBranchId: currentBranchId, forkedFromEventSerial: anchor.createdEventSerial } } }; ledger.consume({ anchorId: anchor.anchorId, fromBranchId: currentBranchId, restoredBranchId: newBranchId, eventSerial: anchor.createdEventSerial }); return restored; }
export function assertActionBranch(actionBranchId: string, stateBranchId: string): void { if (actionBranchId !== stateBranchId) throw new Error('[temporal] stale action from replaced branch'); }
