export type TransgressionReason = 'persistent-stat-growth' | 'repeated-max-hp-growth' | 'extra-natural-turn' | 'repeated-revive' | 'future-power-borrowing' | 'resource-debt' | 'authority-escalation' | 'duplicate-consumed-benefit';
export interface BalanceProfile { readonly trueSelfId: string; readonly incarnationSerial: number; readonly baselineStats: Readonly<Record<string, number>>; readonly naturalScalingAllowances: Readonly<Record<string, number>>; readonly naturalTurnEntitlement: number; readonly reviveAllowance: number; readonly formStancePotential: readonly string[] }
export interface TransgressionEvent { readonly eventId: string; readonly reason: TransgressionReason; readonly trueSelfId: string; readonly incarnationSerial: number; readonly amount: number; readonly eventSerial: number }
export interface TransgressionSentence { readonly sentenceId: string; readonly trueSelfId: string; readonly incarnationSerial: number; readonly createdEventSerial: number; readonly rulePolicyId: string; readonly route: 'kiếp-dẫn'; readonly execution: Readonly<{ type: 'lôi-kiếp'; damageType: 'true'; eraseTrueSelf?: never; suppressReincarnation?: never }> }
const keyOf = (trueSelfId: string, incarnationSerial: number): string => `${trueSelfId}:${incarnationSerial}`;
export class TransgressionLedger {
  readonly profiles = new Map<string, BalanceProfile>(); readonly events: TransgressionEvent[] = []; readonly sentences = new Map<string, TransgressionSentence>();
  enter(profile: BalanceProfile): void { const key = keyOf(profile.trueSelfId, profile.incarnationSerial); if (this.profiles.has(key)) throw new Error(`[balance-ledger] duplicate Bình Thế profile ${key}`); this.profiles.set(key, Object.freeze({ ...profile, baselineStats: Object.freeze({ ...profile.baselineStats }) })); }
  record(event: TransgressionEvent): void { if (!this.profiles.has(keyOf(event.trueSelfId, event.incarnationSerial))) throw new Error('[balance-ledger] Vượt Thế requires an accepted BalanceProfile'); if (!(event.amount > 0) || !Number.isFinite(event.amount)) throw new Error('[balance-ledger] debt amount must be finite and positive'); this.events.push(Object.freeze({ ...event })); }
  debt(trueSelfId: string, incarnationSerial: number): number { return this.events.filter(event => event.trueSelfId === trueSelfId && event.incarnationSerial === incarnationSerial).reduce((sum, event) => sum + event.amount, 0); }
  sentence(record: TransgressionSentence): void { if (record.execution.eraseTrueSelf !== undefined || record.execution.suppressReincarnation !== undefined) throw new Error('[balance-ledger] Lôi Kiếp uses normal damage/death lifecycle; implicit True Self erasure or Reincarnation suppression is forbidden'); this.sentences.set(record.sentenceId, Object.freeze({ ...record })); }
  resolveSentence(sentenceId: string, _context: { side?: string; ownerId?: string; tauntedBy?: string; charmedBy?: string }): TransgressionSentence | undefined { return this.sentences.get(sentenceId); }
}
