import type { SessionState } from '@shared-types/combat';
import type { Side, UnitToken } from '../../types/units.ts';
import { nextEventSerial } from './sequence.ts';
import type { ReincarnationRecord } from './reincarnation.ts';

export interface RebirthRequest { deathId: string; trueSelfId: string; newIid: string | number; authority: 'rebirth'; effectAllowsRebirth: boolean; spawn: { side: Side; cx: number; cy: number }; template: UnitToken; policies: { hp: number | 'full'; rage: number; preserveStatusIds?: readonly string[] } }
export interface RebirthEligibility { allowed: boolean; reason: 'allowed' | 'battle-ended' | 'not-entered' | 'identity-mismatch' | 'missing-authority' | 'effect-blocked' | 'invalid-spawn' | 'iid-conflict' }
export interface RebirthResult { committed: boolean; reason: RebirthEligibility['reason']; trueSelfId: string; oldIid: string | number | null; newIid: string | number | null; incarnationSerial: number }
type TrueSelfRecord = { confirmedKills: number; incarnationSerial: number; deathHistory: string[]; rebirthHistory: Array<{ deathId: string; oldIid: string | number; newIid: string | number; eventSerial: number }> };
type Runtime = { battleEnd?: { ended?: boolean }; reincarnationByDeathId?: Record<string, ReincarnationRecord>; trueSelfRecords?: Record<string, TrueSelfRecord>; combatEvents?: Record<string, unknown>[] };
const rt=(game:SessionState):Runtime=>(game.runtime??={}) as Runtime;
export function evaluateRebirthEligibility(game:SessionState,request:RebirthRequest):RebirthEligibility { const state=rt(game); if(state.battleEnd?.ended)return{allowed:false,reason:'battle-ended'}; const record=state.reincarnationByDeathId?.[request.deathId]; if(!record||record.state!=='entered')return{allowed:false,reason:'not-entered'}; if(record.trueSelfId!==request.trueSelfId)return{allowed:false,reason:'identity-mismatch'}; if(request.authority!=='rebirth')return{allowed:false,reason:'missing-authority'}; if(!request.effectAllowsRebirth)return{allowed:false,reason:'effect-blocked'}; if(!Number.isInteger(request.spawn.cx)||!Number.isInteger(request.spawn.cy)||request.spawn.cx<0||request.spawn.cy<0)return{allowed:false,reason:'invalid-spawn'}; if(game.tokens.some(token=>(token.iid??token.id)===request.newIid))return{allowed:false,reason:'iid-conflict'}; return{allowed:true,reason:'allowed'}; }
/** Serializable consequence hook reserved for the future Axiom registry. */
export function applyRebirthConsequences(_trueSelf:TrueSelfRecord,_request:RebirthRequest):Record<string,never>{return {};}
export function commitRebirth(game:SessionState,request:RebirthRequest):RebirthResult { const eligibility=evaluateRebirthEligibility(game,request); const state=rt(game); const record=state.reincarnationByDeathId?.[request.deathId]; if(!eligibility.allowed||!record)return{committed:false,reason:eligibility.reason,trueSelfId:request.trueSelfId,oldIid:record?.targetIid??null,newIid:null,incarnationSerial:state.trueSelfRecords?.[request.trueSelfId]?.incarnationSerial??1};
  const self=(state.trueSelfRecords??={})[request.trueSelfId]??={confirmedKills:0,incarnationSerial:1,deathHistory:[],rebirthHistory:[]}; self.incarnationSerial+=1; if(!self.deathHistory.includes(record.deathId))self.deathHistory.push(record.deathId); applyRebirthConsequences(self,request);
  const old=game.tokens.find(token=>(token.iid??token.id)===record.targetIid); if(old)(old as UnitToken&{retiredByRebirth?:boolean}).retiredByRebirth=true;
  const keep=new Set(request.policies.preserveStatusIds??[]); const unit={...request.template,iid:request.newIid,trueSelfId:request.trueSelfId,lifeSerial:1,incarnationSerial:self.incarnationSerial,side:request.spawn.side,cx:request.spawn.cx,cy:request.spawn.cy,lifeState:'alive',alive:true,rage:request.policies.rage,statuses:(request.template.statuses??[]).filter(status=>keep.has(String(status.id)))} as UnitToken; unit.hp=request.policies.hp==='full'?Math.max(1,Number(unit.hpMax??1)):Math.max(1,Math.min(Number(unit.hpMax??1),request.policies.hp)); game.tokens.push(unit); record.state='reborn'; const eventSerial=nextEventSerial(game); self.rebirthHistory.push({deathId:record.deathId,oldIid:record.targetIid,newIid:request.newIid,eventSerial}); (state.combatEvents??=[]).push({type:'REBIRTH_COMMITTED',eventSerial,deathId:record.deathId,trueSelfId:request.trueSelfId,oldIid:record.targetIid,newIid:request.newIid,lifeSerial:1,incarnationSerial:self.incarnationSerial}); return{committed:true,reason:'allowed',trueSelfId:request.trueSelfId,oldIid:record.targetIid,newIid:request.newIid,incarnationSerial:self.incarnationSerial}; }

